### ISSUE TITLE
Feature request: set duration while dnd is active

### ISSUE THREAD

**Issue by simon-abbott** [vitorgalvao/calm-notifications-workflow#1]
Currently if Do Not Disturb is enabled and I try to set/change the duration my only option is to turn DnD off. It would be nice if that could be automated as well.

For example, if DnD is enabled, I would expect typing `dnd 1.5h` to either change the end time, or, if that's not possible to do, then it would turn DnD off and back on with the new time.

**Comment by vitorgalvao** [comment]
Thank you for the feature request, but that’s not something I’m thinking of adding. I remember considering it way back when but deciding against it. While I don’t recall all my reasons then, today I’d say there’s little demand for it and adding it would complicate the code while also muddying the interface. To me, getting *the state* of DnD is one of the most important parts and I want that information to always be clear and definitive, not to fluctuate depending on if a number input exists or not. In that sense, having to turn it off first is a feature for me because it makes me mindful of the DnD state and things I might’ve missed.

Do note the workflow has an [External Trigger](https://www.alfredapp.com/help/workflows/triggers/external/), so you can leverage that in another workflow to force the behaviour you want.

**Comment by simon-abbott** [comment]
Fair enough! It would be useful for me, but that's really only because I sometimes fat-finger the input and have to change it, which is definitely user error.

**Comment by vitorgalvao** [comment]
[⤓ Here’s a workflow](https://github.com/vitorgalvao/calm-notifications-workflow/files/10512515/Restart.Do.Not.Disturb.alfredworkflow.zip) to do that. It uses `dnf` (`f` for “fix”) as the keyword.

It’s “quick and dirty”. It works but assumes (and doesn’t check for) that you have the shortcut set up. And it doesn’t check for the current status. It always turns DnD off then on again with the value.
