### ISSUE TITLE
Recover previously used focus mode

### ISSUE THREAD

**Issue by bar-dzi** [vitorgalvao/calm-notifications-workflow#5]
### Feature details

Hi,
Could you add possibilities to remember previously used focus mode and switch between them when "dnd" is executed? Currently flow looks like this:
1. I'm on "Work" focus mode
2. Type "dnd" disabling current "Work" focus mode and start "normal" mode (this should be skipped)
3. Second type "dnd" enabling Do Not Disturb (moon) - expected behaviour
4. Third type "dnd" disabling Do Not Disturb but focus mode not back to "Work", it back to normal mode enabled in step 2.

Best regards!

**Comment by vitorgalvao** [comment]
Thank you for the request, but this is contrary  to the workflow’s goals.

Do Not Disturb is a specific mode of no interruptions, while other modes have particular settings. It wouldn’t make sense to exit Work mode at the end of work then reactivate it when having dinner because you don’t want to be disturbed. Plus it’s yet another thing to think about when typically you want this to be activated fast, often is response to an annoyance.

if you always want to switch to the same mode, you may be able to edit the installed shortcut.
